name: Pull request

on:
  workflow_dispatch:
  pull_request:
  workflow_call:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      # Change connection string 
      - name: edit connection string
        uses: benday-inc/edit-dbconnstr-in-appsettings@main
        with:
          pathtosettingsfile: ./src/SkySensorsAPI/appsettings.json
          name: "Postgres"
          connectionstring: ${{ secrets.CONNECTING_STRING_TEST }}
      - name: edit connection string
        uses: benday-inc/edit-dbconnstr-in-appsettings@main
        with:
          pathtosettingsfile: ./src/SkySensorsAPI.Tests/appsettings.tests.json
          name: "Postgres"
          connectionstring: ${{ secrets.CONNECTING_STRING_TEST }}
      - name: Build and test
        working-directory: ./src/
        run: docker compose --file './docker-compose.yml' --file './docker-compose.override.yml' up --build --abort-on-container-exit --exit-code-from sky-sensors-api.tests sky-sensors-api.tests
