name: Pull request

on:
  workflow_dispatch:
  pull_request:
  workflow_call:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build solution
        working-directory: ./src/
        run: dotnet build

      - name: Run API
        working-directory: ./src/SkySensorsAPI/
        run: dotnet run

      - name: Run Tests
        working-directory: ./src/
        run: dotnet tests