name: Pull request

on:
  workflow_dispatch:
  pull_request:
  workflow_call:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Log into registry skygres
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and test
        working-directory: ./src/
        run: docker compose --file './docker-compose.yml' --file './docker-compose.override.yml' up --build --abort-on-container-exit --exit-code-from sky-sensors-api.tests sky-sensors-api.tests
        env:
          DB_USERNAME: postgres
          DB_PASS: password
          DB_HOST: postgresdb # Use the docker compose service name 
          DB_PORT: 5432
          DB_NAME: postgres
